CREATE PROC FI_SP_AltBeneficiario
    @NOME          VARCHAR (50) ,
	@CPF		   VARCHAR (11),
	@IDCLIENTE		BIGINT,
	@Id           BIGINT
AS
BEGIN
delete from Beneficiarios where IDCLIENTE = @IDCLIENTE;

	INSERT INTO BENEFICIARIOS (NOME, CPF, IDCLIENTE) 
	VALUES (@NOME, @CPF, @IDCLIENTE)
	
END